# 7-jammy
services:
  mongodb:
    
    image: mongo:7-jammy
    
    container_name: mongodb
    
    ports:
      - "27007:27017"
    
    volumes:
      - "./mongodb:/data/db"
    
    networks:
      - backend
    
    # if fauild restart
    restart: always




networks:
  backend:
